### ISSUE TITLE
Lage ETL jobber for alle relevante kataloger ifm migrering fra data.norge

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataset-etl#1]
Skal i hovedsak kunne benytte API'et til data.norge:
https://data.norge.no/api/dcat/991825827/data.json

Kan ta utgangspunkt i noen ETL jobber Stig allerede har laget.
@stigbd  legger inn lenke her

- [x] ETL for Dataset Catalog

- [x] Må vi gjøre noe med databasen hos oss?

- [x] Få databasedumpen over på objektorientert JSON-format

- [x] Mappe JSON-format om til FDK-format

- [x] Oppdatering av de to api'ene (slik at admin kan lagre på vegne av andre)

- [ ] Lagre via apiene (dataset-catalogue & dataservice-catalog)
